package com.jee_project;

import jakarta.annotation.Resource;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.metamodel.EntityType;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import javax.sql.DataSource;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.SQLException;
import java.util.Set;

@WebServlet(value = "/test-db")
public class DatabaseConnectionTest extends HttpServlet {

    @Resource(name = "smsDS")
    private DataSource dataSource;

    @PersistenceContext(unitName = "smsPU")
    private EntityManager entityManager;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {

        resp.setContentType("text/html;charset=UTF-8");
        PrintWriter out = resp.getWriter();

        // Write Header with Tailwind CDN
        out.println("<!DOCTYPE html>");
        out.println("<html lang='en'>");
        out.println("<head>");
        out.println("<meta charset='UTF-8'>");
        out.println("<meta name='viewport' content='width=device-width, initial-scale=1.0'>");
        out.println("<title>System Health Check</title>");
        out.println("<script src='https://cdn.tailwindcss.com'></script>");
        out.println("</head>");
        out.println("<body class='bg-slate-50 text-slate-900 font-sans min-h-screen p-8'>");

        // Container
        out.println("<div class='max-w-3xl mx-auto space-y-6'>");

        // Header Section
        out.println("<div class='flex justify-between items-center mb-8'>");
        out.println("<div>");
        out.println("<h1 class='text-3xl font-bold tracking-tight text-slate-900'>System Diagnostics</h1>");
        out.println("<p class='text-slate-500 mt-1'>Database Connection & JPA Persistence Check</p>");
        out.println("</div>");
        out.println("<a href='index.jsp' class='px-4 py-2 bg-white border border-slate-300 rounded-md text-sm font-medium text-slate-700 hover:bg-slate-50 transition'>&larr; Back to Home</a>");
        out.println("</div>");

        // Test 1: DataSource
        testDataSource(out);

        // Test 2: EntityManager
        testEntityManager(out);

        // Close Container & Body
        out.println("<div class='text-center text-xs text-slate-400 mt-10'>Generated by DatabaseConnectionTest Servlet</div>");
        out.println("</div>"); // End Container
        out.println("</body></html>");
    }

    private void testDataSource(PrintWriter out) {
        out.println("<div class='bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden'>");
        out.println("<div class='px-6 py-4 border-b border-slate-100 bg-slate-50 flex justify-between items-center'>");
        out.println("<h2 class='font-semibold text-slate-800'>1. JDBC DataSource (smsDS)</h2>");
        out.println("</div>");

        out.println("<div class='p-6'>");

        if (dataSource == null) {
            printError(out, "DataSource Injection Failed", "The @Resource injection for 'smsDS' returned null.");
            out.println("</div></div>");
            return;
        }

        try (Connection conn = dataSource.getConnection()) {
            if (conn != null) {
                DatabaseMetaData metaData = conn.getMetaData();

                printSuccessBadge(out, "Connection Established");

                out.println("<div class='grid grid-cols-1 md:grid-cols-2 gap-4 mt-4 text-sm'>");
                printInfoRow(out, "Database Product", metaData.getDatabaseProductName());
                printInfoRow(out, "Product Version", metaData.getDatabaseProductVersion());
                printInfoRow(out, "Driver Name", metaData.getDriverName());
                printInfoRow(out, "JDBC URL", metaData.getURL());
                printInfoRow(out, "Db User", metaData.getUserName());
                out.println("</div>");
            }
        } catch (SQLException e) {
            printError(out, "SQL Exception", e.getMessage());
            e.printStackTrace(); // Optional: prints to server logs
        }

        out.println("</div></div>"); // End Card
    }

    private void testEntityManager(PrintWriter out) {
        out.println("<div class='bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden'>");
        out.println("<div class='px-6 py-4 border-b border-slate-100 bg-slate-50 flex justify-between items-center'>");
        out.println("<h2 class='font-semibold text-slate-800'>2. JPA EntityManager (smsPU)</h2>");
        out.println("</div>");

        out.println("<div class='p-6'>");

        if (entityManager == null) {
            printError(out, "EntityManager Injection Failed", "The @PersistenceContext injection returned null.");
            out.println("</div></div>");
            return;
        }

        try {
            // Test simple query
            entityManager.createNativeQuery("SELECT 1").getSingleResult();
            printSuccessBadge(out, "Persistence Context Active");

            // Get Metamodel
            Set<EntityType<?>> entities = entityManager.getMetamodel().getEntities();

            out.println("<div class='mt-6'>");
            out.println("<p class='text-sm font-medium text-slate-500 uppercase tracking-wide mb-3'>Registered Entities (" + entities.size() + ")</p>");

            if (!entities.isEmpty()) {
                out.println("<div class='flex flex-wrap gap-2'>");
                for (EntityType<?> entity : entities) {
                    out.println("<span class='inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-cyan-100 text-cyan-800'>");
                    out.println(entity.getName());
                    out.println("</span>");
                }
                out.println("</div>");
            } else {
                out.println("<p class='text-sm text-yellow-600'>No entities found. Check your persistence.xml mapping.</p>");
            }
            out.println("</div>");

        } catch (Exception e) {
            printError(out, "Persistence Error", e.getMessage());
            e.printStackTrace();
        }

        out.println("</div></div>"); // End Card
    }

    // --- Helper Methods for Styling ---

    private void printInfoRow(PrintWriter out, String label, String value) {
        out.println("<div class='bg-slate-50 p-3 rounded border border-slate-100'>");
        out.println("<span class='block text-xs font-bold text-slate-400 uppercase'>" + label + "</span>");
        out.println("<span class='block text-slate-800 font-mono text-xs truncate' title='" + value + "'>" + value + "</span>");
        out.println("</div>");
    }

    private void printSuccessBadge(PrintWriter out, String message) {
        out.println("<div class='flex items-center text-green-700 bg-green-50 border border-green-200 p-4 rounded-lg'>");
        out.println("<span class='text-xl mr-3'>✅</span>");
        out.println("<span class='font-medium'>" + message + "</span>");
        out.println("</div>");
    }

    private void printError(PrintWriter out, String title, String message) {
        out.println("<div class='bg-red-50 border-l-4 border-red-500 p-4'>");
        out.println("<div class='flex'>");
        out.println("<div class='flex-shrink-0'><span class='text-red-500 text-xl'>❌</span></div>");
        out.println("<div class='ml-3'>");
        out.println("<h3 class='text-sm font-medium text-red-800'>" + title + "</h3>");
        out.println("<div class='mt-2 text-sm text-red-700'><p>" + message + "</p></div>");
        out.println("</div></div></div>");
    }
}